spring:
  datasource:
    graph:
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.vesoft.nebula.jdbc.NebulaDriver
      url: jdbc:nebula://localhost:9669/basketballplayer?characterEncoding=utf8
      username: root
      password: 123
      hikari:
        minimum-idle: 5
        # 空闲连接存活最大时间，默认600000（10分钟）
        idle-timeout: 180000
        # 连接池最大连接数，默认是10
        maximum-pool-size: 20
        # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
        auto-commit: true
        # 连接池名称
        pool-name: GraphHikariCP
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        max-lifetime: 1800000
        # 数据库连接超时时间,默认30秒，即30000
        connection-timeout: 30000
        connection-test-query: RETURN 1